Signup testing
wolox-training/gb-express-js pull request #9
Opened 2017-07-18 19:09 UTC by gabybrow

## Summary
- Signup endpoint tests

## Trello Card
https://trello.com/c/KSFYVYuL/33-tests-y-documentaci%C3%B3n-de-sign-up

2017-07-19 17:35 UTC, gabybrow commented
Travis is rejecting the pull request because it is not finding the database url environment variable

2017-07-19 19:06 UTC, mpizzagalli requested changes

2017-07-19 19:06 UTC, mpizzagalli commented on test/users.js
> +        // dictum.chai(err);
Remove all this comments

2017-07-19 19:06 UTC, mpizzagalli commented on app/models/scripts/dataCreation.js
> +  // orm.models.user.create({ firstName: 'test', lastName: 'wolox', password: '123456789', email: 'test@wolox.com.ar' }).then();
We should try figure out why this isn't working right, so we can add it in this PR.

2017-07-21 17:16 UTC, mpizzagalli requested changes

2017-07-21 17:16 UTC, mpizzagalli commented on test/users.js
> +  orm = require('../app/orm'),
you don't need this require anymore.

2017-07-21 17:16 UTC, mpizzagalli commented on test/users.js
> +        err.response.body.should.have.property('error');
You could also check that the error message is the one we expect in this case `The password is too short`

2017-07-21 17:16 UTC, mpizzagalli commented on test/users.js
> +        err.response.body.should.have.property('error');
same here

2017-07-21 17:16 UTC, mpizzagalli commented on test/users.js
> +        err.response.body.should.have.property('error');
same here

2017-07-21 17:16 UTC, mpizzagalli commented on test/users.js
> +        res.should.have.status(200);
Here we could also check that we actually have created a new user, but for now its ok without checking.

2017-07-21 20:44 UTC, mpizzagalli approved these changes

2017-07-24 12:53 UTC, merged